server:
  port: 8080
  context-path: /springbootdemo/
  tomcat:
    max-connections: 300
    max-threads: 1000
spring:
  datasource:
    name: carservicedev
    url: jdbc:mysql://10.10.10.13:3306/carserviceres?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /resource/
      suffix: .jsp
  session:
    store-type: none
  freemarker:
    check-template-location: false
  jmx:
    enabled: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:public/mybatis-configuration.xml
